♻️ Refactor Logger
PaiGramTeam/MeidoChan pull request #1
Opened 2024-01-03 03:47 UTC by karakoo

2024-01-03 05:33 UTC, karakoo commented
剩下的需要 config 重构之后才能写

2024-01-04 04:32 UTC, luoshuijs approved these changes

2024-01-04 05:59 UTC, omg-xtao requested changes

2024-01-04 05:59 UTC, omg-xtao commented on src/meido/utils/log/_handler.py
> +def resolve_log_path(path: str | Path, root: Path = Path(os.curdir).resolve()) -> str:
```
[2024-01-04 13:52:24] INFO     1                                   <SITE> 1489 
                      SUCCESS  2                                     test 6    
                      WARNING  3                                   <SITE> 1501 
```

仅 success 日志的路径渲染正常

2024-01-04 05:59 UTC, omg-xtao commented on src/meido/utils/log/_logger.py
>          return cls._instance
```suggestion
        if not cls._instance:
            with cls._lock:
                cls._instance = super(LoggerMeta, cls).__call__(*args, **kwargs)
        return cls._instance
```

2024-01-04 07:24 UTC, karakoo commented on src/meido/utils/log/_handler.py
> +def resolve_log_path(path: str | Path, root: Path = Path(os.curdir).resolve()) -> str:
待我修修看

2024-01-04 07:25 UTC, karakoo commented on src/meido/utils/log/_logger.py
>          return cls._instance
测试时忘了改回去

2024-01-04 08:46 UTC, luoshuijs commented on src/meido/utils/log/_logger.py
>          return cls._instance
话说这个 suggest change ， with 放在变量 读/写 的中间，这不是跟没加锁一样嘛?

2024-01-04 08:59 UTC, luoshuijs approved these changes

2024-01-04 09:02 UTC, omg-xtao approved these changes

2024-01-04 09:11 UTC, luoshuijs commented on src/meido/utils/log/_logger.py
> +NONE = object()
要不要改成

`DEFAULT_NONE = TypeVar('DEFAULT_NONE', bound=object)`

2024-01-05 04:03 UTC, merged